controllers:
    host: 'ojbento.fr'
    resource: ../../src/Controller/
    type: annotation

api_auth_login:
    host: 'api.ojbento.fr'
    path: /login_check
    methods: [POST]

api_controller:
    host: 'api.ojbento.fr'
    resource: ../../src/ApiController/
    type: annotation